import sqlite3


conn = sqlite3.connect('ksd_knowledge.db')
cur = conn.cursor()

rules = [
    # LESSON 17: §170-§174
    ('tense', 'present_passive_formation',
     'Present passive is formed from the passive stem, made by adding [-i-] to the active stem, plus present-tense endings. It is common chiefly in 3s. and 3p.; there are no present passive forms with [-v-]. Usual 3s. ending is [-iai], often with variants [-ijai] and less commonly [-iale]. Verbs with stems in [-e] and [-ai] have common irregular 3s. forms in [-ijai].',
     'ਪਾਈਐ / ਪਾਈਅਨਿ / ਪਾਈਅਹਿ | ਧਰੀਐ=ਧਰੀਜੇ | ਦੀਜੇ | ਲੀਜੇ=ਲੀਜੈ | ਕਰੀਐ=ਕਰੀਜੇ=ਕੀਜੇ=ਕੀਚੈ',
     'ਪਾਈਐ = he is found | ਪਾਈਅਨਿ/ਪਾਈਅਹਿ = they are found | ਧਰੀਐ/ਧਰੀਜੇ = he is put | ਦੀਜੇ = he is given | ਕੀਜੇ/ਕੀਚੈ = it is done',
     'shackle_L17_p109_p110'),
    ('tense', 'present_passive_functions',
     'Present passive is used with a straightforward passive meaning, but many SLS intransitives already have passive-like meanings and do not require a passive form. The 3s. present passive is also frequently used as a gerundive, expressing obligation or what should be done; with intransitives this often becomes impersonal.',
     'ਪਾਈਅਹਿ / ਸੁਟੀਅਹਿ | ਤਰੈ / ਤਾਰੈ | ਵੀਸਰੈ / ਵਿਸਾਰੈ | ਕਮਾਈਐ | ਧਿਆਈਐ | ਰਹੀਐ',
     'ਪਾਈਅਹਿ = are placed/found | ਸੁਟੀਅਹਿ = are cast | ਤਰੈ = he is saved | ਤਾਰੈ = he saves | ਧਿਆਈਐ = is to be meditated upon | ਰਹੀਐ = how is one to endure',
     'shackle_L17_p110'),
    ('word_form', 'absolutive_compounds_with_rahi',
     'The verb [rahi] "live, remain, endure" combines with the absolutive of another verb to form compounds meaning "remain in the state of doing".',
     'ਡਰਿ ਰਹੈ / ਰਹਿ ਰਹੇ',
     'ਡਰਿ ਰਹੈ = remains in fear | ਰਹਿ ਰਹੇ = remains engrossed, stays in that state',
     'shackle_L17_p111'),
    ('principle', 'initial_bhi_conjunction',
     '[bhī] is used both as an emphatic enclitic meaning "even, also" and sentence-initially to introduce a clause meaning "even so, even then, although". Initial ਭੀ differs from enclitic ਭੀ; initial ਤਾਂ means "then", enclitic ਤਾਂ means "but/on the other hand", and ਹੀ never stands first.',
     'ਭੀ ... | ... ਭੀ ... | ਤਾਂ ... | ... ਤਾਂ ... | ... ਹੀ ...',
     'initial ਭੀ = even so/even then | enclitic ਭੀ = also/even | initial ਤਾਂ = then | enclitic ਤਾਂ = but/on the other hand | ਹੀ = just/only',
     'shackle_L17_p111'),
    ('principle', 'repetition_of_words',
     'Repeated absolutives express continual action. Nouns, adjectives, and adverbs may also be repeated: simple repetition can convey universal distribution, while repetition for emphasis often lengthens the final vowel of the first member ([a] to [ā], [i] to [e], [u] to [o]). Other repeated forms are usually translated straightforwardly.',
     'ਨਚਿ ਨਚਿ | ਜੁਗਿ ਜੁਗਿ | ਜਹ ਜਹ | ਨੇੜਾ ਨੇੜ | ਮੁਖੋ ਮੁਖਿ | ਸਚੇ ਸਚੁ | ਜਾਗਹੁ ਜਾਗਹੁ | ਹਰਿ ਹਰਿ',
     'ਨਚਿ ਨਚਿ = dancing and dancing | ਜੁਗਿ ਜੁਗਿ = in each and every age | ਨੇੜਾ ਨੇੜ = for ever and ever | ਮੁਖੋ ਮੁਖਿ = right on the face | ਸਚੇ ਸਚੁ = total truth',
     'shackle_L17_p111_p112'),

    # LESSON 18: §180-§182
    ('word_form', 'nonfinite_verbal_forms_overview',
     'Besides inflected tenses, SLS has verbal forms that are indeclinable or declined as nouns/adjectives: absolutive, infinitive, gerundive, past participle, and present participle. The absolutive normally adds [-i], exceptionally lengthened [-ī]; vowel stems in [-ī], [-e], and [-ai] often do not add an ending. The particle [kai] may extend the absolutive.',
     'ਕਰਿ=ਕਰੀ | ਜਾਇ=ਜਾਈ | ਪੀ | ਦੇ | ਲੇ | ਕਰਿ ਕੈ | ਪੀ ਕੈ',
     'ਕਰਿ/ਕਰੀ = having done | ਜਾਇ/ਜਾਈ = having gone | ਪੀ = having drunk | ਦੇ = having given | ਕਰਿ ਕੈ = having done | ਪੀ ਕੈ = having drunk',
     'shackle_L18_p115'),
    ('word_form', 'infinitive_and_verbal_agent',
     'The infinitive is a verbal noun. Consonant stems take [-aṇu], while vowel stems take [-vaṇu] or [-ṇu]. It declines like a masculine declension I noun with direct, oblique, and locative forms. Oblique and locative infinitives form compound verbs. The verbal agent is formed by adding [-hāru] to the oblique infinitive.',
     'ਕਰਣੁ / ਕਰਣ=ਕਰਣੇ / ਕਰਣਿ | ਜਾਵਣੁ=ਜਾਣ / ਜਾਵਣ=ਜਾਵਣੇ=ਜਾਣ=ਜਾਣੇ / ਜਾਵਣਿ=ਜਾਣਿ | ਕਰਣਹਾਰੁ=ਕਰਣੈਹਾਰੁ',
     'ਕਰਣੁ = to do, doing | ਕਰਣਿ = in doing | ਜਾਣ = to go, going | ਕਰਣਹਾਰੁ = doer, creator',
     'shackle_L18_p115_p116'),
    ('word_form', 'gerundive_formation_and_sense',
     'The gerundive is a verbal adjective, formed like the infinitive but ending in [-ṇā] rather than [-ṇu], with some overlap between infinitive and gerundive forms. It usually has a passive sense "to be done", though some forms have active adjectival meanings.',
     'ਕਰਣਾ | ਡਰਾਵਣਾ | ਮਾਣਸ ਖਾਣੇ',
     'ਕਰਣਾ = to be done | ਡਰਾਵਣਾ = frightening | ਮਾਣਸ ਖਾਣੇ = man-eating, cruel',
     'shackle_L18_p116'),
    ('tense', 'present_tense_full_range_consonant_stems',
     'The present tense is the commonest finite verb form and has many personal endings. Consonant-stems have a broad paradigm: 1s. [-ām], [-īm], [-aum]; 2s. [-amhi], [-aim], [-em]; 3s. [-ai], [-e], [-aī], with rarer [-ae], [-asi] and extended [-ei]; 1p. [-amha]; 2p. [-ahu]; 3p. [-anhi], [-anhī], [-amhi], [-amhī], with extended [-enhi], [-emhi]. Extended [-e-] forms are typically used in rhyme.',
     'ਕਰਾਂ / ਕਰੀ / ਕਰਉ | ਕਰਹਿ / ਕਰੇ | ਕਰੈ / ਕਰੇ / ਕਰਈ | ਕਰਹ / ਕਰਹੁ | ਕਰਨਿ / ਕਰਣੀ / ਕਰਹਿ / ਕਰਹੀ',
     'ਕਰਾਂ/ਕਰੀ/ਕਰਉ = I do | ਕਰਹਿ/ਕਰੇ = you do | ਕਰੈ/ਕਰੇ/ਕਰਈ = he does | ਕਰਹੁ = you do (pl.) | ਕਰਨਿ/ਕਰਹਿ = they do',
     'shackle_L18_p116_p117'),
    ('tense', 'present_tense_vowel_stems',
     'Vowel-stems form the present either with [-v-], following consonant-stem endings, or without [-v-], where personal endings are often contracted. Vowel-stems also have forms with [-i-] in the 2p. and 3p.; these are part of the full present-tense range. Verbs [pai] and [lai] have additional irregular present forms.',
     'ਪਾਵਾਂ / ਪਾਵੀਂ / ਪਾਵਉ | ਪਾਵਹਿ | ਪਾਵੈ / ਪਾਵਈ | ਪਾਵਹ / ਪਾਵਹੁ | ਪਾਵਨਿ / ਪਾਵਹਿ | ਪਾਈ / ਪਾਉ / ਪਾਹਿ / ਪਾਇਨਿ',
     'ਪਾਵਾਂ = I find | ਪਾਵੈ/ਪਾਏ/ਪਾਇ/ਪਾਈ = he finds | ਪਾਵਨਿ/ਪਾਵਹਿ/ਪਾਇਨਿ/ਪਾਹਿ = they find',
     'shackle_L18_p117_p118'),
    ('tense', 'future_and_imperative_overview',
     'The future tense is most often formed by endings beginning with [-s-], which except in the 3s. are identical with the normal present-tense endings. Consonant stems may have extended S-futures with [-e-]; vowel stems may have extended forms with [-i-] before personal endings, and [-v-] is not often used for vowel-stem futures. The imperative is normally limited to 2s. and 2p., though occasional 3s. and 3p. forms occur.',
     'ਕਰਸੀ=ਕਰੇਸੀ | ਪਾਸੀ=ਪਾਇਸੀ',
     'ਕਰਸੀ/ਕਰੇਸੀ = he will do | ਪਾਸੀ/ਪਾਇਸੀ = he will find/get',
     'shackle_L18_p118_p119'),

    # LESSON 19: §190-§193
    ('word_form', 'past_participle_regular_formation',
     'The past participle expresses completed action or past time. Regular masculine singular direct is formed by adding [-iā] to the verbal stem, without distinction between consonant and vowel stems. It inflects like an adjective of declension AII; direct forms include masculine singular [-iā], masculine plural [-e], feminine singular [-ī], feminine plural [-īāṃ].',
     'ਚਲਿ → ਚਲਿਆ / ਚਲੇ / ਚਲੀ / ਚਲੀਆਂ | ਆਇ → ਆਇਆ / ਆਏ / ਆਈ / ਆਈਆਂ',
     'ਚਲਿਆ = departed | ਆਇਆ = came | ਚਲੇ/ਆਏ = masculine plural | ਚਲੀ/ਆਈ = feminine singular | ਚਲੀਆਂ/ਆਈਆਂ = feminine plural',
     'shackle_L19_p121'),
    ('word_form', 'irregular_past_participles_vowel_before_aa',
     'Irregular past participles may have a vowel before final [-ā]. Vowel-stems ending in [-ī] add [-ā], not [-iā]; some consonant-stems also have [-ā]. Common classes include pp. in [-īā], [-ūā], and [-aiā], and the same verb may have several related irregular participles.',
     'ਥੀ → ਥੀਆ | ਪੀ → ਪੀਆ | ਡੁਭਿ → ਡੁਭਾ | ਟੁਟਿ → ਟੁਟਾ | ਲਗਿ → ਲਗਾ | ਕਰਿ → ਕੀਆ | ਦੇ → ਦੀਆ | ਲੇ → ਲੀਆ | ਹੋਇ → ਹੂਆ=ਹੋਇਆ | ਜਾਇ → ਗਇਆ | ਪੈ → ਪਇਆ | ਲੈ → ਲਇਆ',
     'ਥੀਆ = became | ਪੀਆ = drunk | ਡੁਭਾ = sank/drowned | ਟੁਟਾ = broken | ਕੀਆ = done | ਦੀਆ = given | ਗਇਆ = gone | ਪਇਆ = fallen | ਲਇਆ = taken',
     'shackle_L19_p121_p122'),
    ('tense', 'past_tense_intransitive_agreement',
     'The past participle commonly functions as a past tense. With intransitive verbs it agrees with the subject in gender and number; the same forms may be translated contextually as simple past, perfect, pluperfect, or stative result.',
     'ਹਉ ਗਇਆ / ਹਉ ਗਈ | ਤੂੰ ਗਇਆ / ਤੂੰ ਗਈ | ਸੋ ਗਇਆ / ਸਾ ਗਈ | ਹਮ ਗਏ / ਹਮ ਗਈਆਂ | ਤੁਮ ਗਏ / ਤੁਮ ਗਈਆਂ | ਸੇ ਗਏ / ਸੇ ਗਈਆਂ',
     'ਹਉ ਗਇਆ = I went (m.) | ਹਉ ਗਈ = I went (f.) | ਸੇ ਗਏ = they went (m.) | ਸੇ ਗਈਆਂ = they went (f.)',
     'shackle_L19_p123'),
    ('word_form', 'past_participle_adjective_and_noun',
     'The past participle is formally an adjective and may be used adjectivally; it may also be used as a noun meaning "what has been done". Such nominal participles can mean an utterance, writing, reading, or other completed result.',
     'ਭਰਿਆ | ਨੀਰਿ ਭਰਿਆ | ਕਹਿਆ=ਆਖਿਆ | ਲਿਖਿਆ | ਪੜਿਆ',
     'ਭਰਿਆ = filled, full | ਨੀਰਿ ਭਰਿਆ = filled with water | ਕਹਿਆ/ਆਖਿਆ = what has been said, word, utterance | ਲਿਖਿਆ = written, fate | ਪੜਿਆ = read, learned man',
     'shackle_L19_p123_p124'),

    # LESSON 20: §200-§203
    ('word_form', 'irregular_past_participles_consonant_before_aa',
     'Most irregular past participles have a retroflex or dental consonant before final [-ā] of the masculine singular. They are historically determined and generally unpredictable, so each must be learnt individually. Many verbs also have regular participles in [-iā], but the irregular classes are grouped by the consonant before final [-ā].',
     'ਕੁਠਾ / ਢਠਾ / ਤੁਠਾ / ਡਿਠਾ=ਡੀਠਾ / ਬੈਠਾ / ਵੁਠਾ | ਸਮਾਣਾ / ਕਮਾਣਾ / ਭਾਣਾ | ਵੁਠਾ | ਸੁਤਾ / ਕੀਤਾ=ਕੀਆ / ਜਾਤਾ / ਦਿਤਾ=ਦੀਆ / ਧੋਤਾ / ਨਾਤਾ / ਪਛਾਤਾ / ਪੀਤਾ=ਪੀਆ / ਰਤਾ | ਖੁਥਾ / ਫਾਥਾ / ਲਥਾ | ਖਾਧਾ / ਪੈਧਾ / ਬਧਾ=ਬਾਧਾ / ਲਧਾ | ਉਪਨਾ / ਭਿੰਨਾ=ਭੀਨਾ / ਰੁੰਨਾ',
     'ਕੁਠਾ = slaughtered | ਡਿਠਾ = seen | ਸਮਾਣਾ = contained | ਕੀਤਾ = done | ਦਿਤਾ = given | ਪੀਤਾ = drunk | ਖਾਧਾ = eaten | ਲਧਾ = obtained | ਉਪਨਾ = created',
     'shackle_L20_p126_p128'),
    ('tense', 'ergative_past_transitive_construction',
     'Because the past participle has a passive sense, transitive past tense uses an ergative construction: the logical subject appears in locative/instrumental (agentive) case rather than direct case, and the participle agrees not with that logical subject but with the logical object in direct case. A literal passive rendering may be possible, but this is the normal SLS way to express "X did Y" in the past.',
     'ਗੁਰੁ ਆਵੈ / ਗੁਰੁ ਆਇਆ | ਗੁਰੁ ਦੇਵੈ / ਗੁਰਿ ਦਿਤਾ | ਮੂਰਖਿ ਅੰਧੈ ਪਤਿ ਗਵਾਈ | ਗੁਰਿ ਰਾਖੇ ਸੇ ਉਬਰੇ | ਬਾਦਿ ਕਾਰਾ ਸਭਿ ਛੋਡੀਆਂ',
     'ਗੁਰਿ ਦਿਤਾ = the Guru gave | ਪਤਿ ਗਵਾਈ = honour was lost | ਗੁਰਿ ਰਾਖੇ = preserved by the Guru | ਛੋਡੀਆਂ = were forsaken',
     'shackle_L20_p128_p129'),
    ('case', 'ergative_pronoun_forms',
     'Singular demonstrative/relative pronouns used as logical subjects in ergative constructions appear in their special agentive forms with [-n-] of the singular locative. Personal pronouns, which have no special locative case, appear in the oblique. Other pronouns and nouns may exceptionally appear in the oblique instead of the locative without changing the meaning.',
     'ਜਿਨਿ ਸੇਵਿਆ ਤਿਨਿ ਪਾਇਆ ਮਾਨੁ | ਕਿਨੇ ਅੰਤੁ ਨ ਪਾਇਆ | ਇਹਿ ਮਾਇਆ ਜਗੁ ਮੋਹਿਆ | ਤੁਧੁ ਜਗਤੁ ਉਪਾਇਆ | ਸਤਿਗੁਰੁ ਬੂਝ ਬੁਝਾਈ',
     'ਜਿਨਿ/ਤਿਨਿ = by whom/by him | ਕਿਨੇ = by anyone | ਇਹਿ = by this | ਤੁਧੁ = by you | ਸਤਿਗੁਰੁ = by the True Guru (oblique exception)',
     'shackle_L20_p129'),
    ('principle', 'transitive_intransitive_distinction',
     'The distinction between transitive and intransitive verbs in SLS is close to English: transitives may take a direct object, intransitives may not. Some translation equivalents are misleading: [mili] "meet" basically means "come to" and is intransitive, while [jīti] "win" basically means "defeat", and [hāri] "lose" can take the ergative construction in the past.',
     'ਹਰਿ ਪ੍ਰੇਮਿ ਮਿਲੀ | ਜਰੁ ਜੀਤਿਆ | ਜਰੁ ਆਈ ਜੋਬਨਿ ਹਾਰਿਆ',
     'ਮਿਲੀ = met/came to, intransitive | ਜੀਤਿਆ = defeated/won, transitive | ਹਾਰਿਆ = lost, transitive past with ergative sense',
     'shackle_L20_p130'),
    ('word_form', 'verb_to_be_present_forms',
     'The verb "to be" is often omitted in simple SLS sentences. Besides [hoi] and [thī] "be, become", there is a full set of present forms in addition to common 3s. [hai]: 1s. hāṃ, 2s. hahi/haiṃ, 3s. hai, 1p. hāṃ, 2p. hahu, 3p. hahi/hai/hain(i). Forms other than 3s. are not frequent.',
     'ਹਾਂ | ਹਹਿ=ਹੈਂ | ਹੈ | ਹਹੁ | ਹਹਿ=ਹੈ=ਹੈਨਿ',
     'ਹਾਂ = I am/we are | ਹਹਿ/ਹੈਂ = you are | ਹੈ = he is | ਹਹੁ = you are (pl.) | ਹਹਿ/ਹੈਨਿ = they are',
     'shackle_L20_p130'),

    # LESSON 21: §210-§214
    ('word_form', 'past_participle_variant_o_and_passive_overlap',
     'Like adjectives in [-ā], the past participle may have masculine singular direct in [-o] instead of [-ā]. There is also overlap between the 3s. present passive and the past participle: indeclinable past participles in [-iai], sometimes [-iale], are formally identical with 3s. present passive forms and may mark past passive/resultative meaning.',
     'ਪਾਇਓ=ਪਾਇਆ | ਗਇਓ=ਗਇਆ | ਦਿਤੋ=ਦਿਤਾ | ਉਪਾਈਐ | ਬਸੀਅਲੇ',
     'ਪਾਇਓ = found | ਗਇਓ = gone | ਦਿਤੋ = given | ਉਪਾਈਐ = was created | ਬਸੀਅਲੇ = have settled',
     'shackle_L21_p133'),
    ('tense', 'perfect_with_auxiliary',
     'The past participle alone often covers both English simple past and perfect. Perfect meaning may be made explicit with forms of the verb "to be" used with the participle, but the presence or absence of the auxiliary normally does not seriously affect meaning.',
     'ਆਇਆ ਹੈ ਉਨਿ ਚਲਣਾ',
     'ਆਇਆ ਹੈ = has come; with the auxiliary the perfect is explicit, but the participle alone can carry the same force',
     'shackle_L21_p133'),
    ('word_form', 'past_participle_infinitive_with_jai',
     'The past participle with [jai] "go" conveys passive possibility and is normally used in the negative with the sense "cannot be done"; both participle and [jai] agree with the subject. The negative may be omitted in questions. A similar impossibility sense is expressed by infinitive direct forms in [-ṇu]/[-nu] or by gerundives with [jai]. Negative present passive overlaps functionally with these compounds.',
     'ਹੁਕਮੁ ਨ ਕਹਿਆ ਜਾਈ | ਤਾ ਕੀਆ ਗਲਾ ਕਥੀਆ ਨ ਜਾਹਿ | ਕਿਆ ਉਪਮਾ ਤੇਰੀ ਆਖੀ ਜਾਇ | ਕੀਮਤਿ ਕਹਣੁ ਨ ਜਾਇ | ਤਾ ਕੇ ਰੂਪ ਨ ਕਥਨੇ ਜਾਹਿ | ਬਿਨੁ ਸਤਿਗੁਰ ਨਾਮੁ ਨ ਪਾਈਐ',
     'ਨ ਕਹਿਆ ਜਾਈ = cannot be spoken | ਕਥੀਆ ਨ ਜਾਹਿ = cannot be uttered | ਆਖੀ ਜਾਇ = can be uttered | ਕਹਣੁ ਨ ਜਾਇ = cannot be spoken | ਨ ਪਾਈਐ = is not to be found/cannot be found',
     'shackle_L21_p134'),
    ('word_form', 'past_rahi_absolutive_compounds',
     'When [rahi] is used in the past with an absolutive compound, the meaning is "has remained in a state of doing/being" or "is in a permanent state of doing/being".',
     'ਸਚਾ ਰਵਿ ਰਹਿਆ ਪ੍ਰਭੁ ਸੋਇ',
     'ਰਵਿ ਰਹਿਆ = has pervaded and has remained doing so',
     'shackle_L21_p134_p135'),
    ('word_form', 'past_participle_pronominal_suffixes',
     'Pronominal subject suffixes may be added to the past participle when it functions as a past tense. These suffixes can equal a pronoun in locative/agentive or direct case. The common suffix [-nu] is equivalent to [tini] and is added to transitive past participles whose form is determined by the logical object. Other suffixes, including 1s. [-imu]/[-umai] with transitives and [-asu]/[-āsi] with intransitives, also occur but are less common.',
     'ਰਖਿਓਨੁ=ਤਿਨਿ ਰਖਿਆ | ਰਖਿਅਨੁ=ਤਿਨਿ ਰਖੇ | ਰਖੀਅਨੁ=ਤਿਨਿ ਰਖੀ/ਰਖੀਆਂ | ਉਪਾਈਅਨੁ | ਠਾਕਿਓਮੁ | ਡਿਠੋਮੈ | ਹਉ ਆਵਣਿ ਜਾਣਿ ਮੁਈਆਸਿ',
     'ਰਖਿਓਨੁ = he preserved it | ਉਪਾਈਅਨੁ = he created them/all | ਡਿਠੋਮੈ = I have seen | ਮੁਈਆਸਿ = I have died',
     'shackle_L21_p135'),

    # LESSON 22: §220-§223
    ('word_form', 'present_participle_t_forms',
     'The present participle corresponds to English "doing, being" and is inflected as an adjective. T-forms are made with [-tā], declined like adjective declension AII, or [-tu], declined like AI. Consonant stems take [-atā]/[-atu]; vowel-stems may take [-vatā]/[-vatu] or short [-tā]/[-tu]. Masculine singular direct in [-tā] often has variant [-to] or [-tau]; rare variants include [-antā]/[-antu].',
     'ਚਲਿ → ਚਲਤਾ=ਚਲਤੁ | ਜੀਵਿ → ਜੀਵਤਾ=ਜੀਵਤੁ | ਜਾਇ → ਜਾਵਤਾ=ਜਾਵਤੁ=ਜਾਤਾ=ਜਾਤੁ | ਹੋਤਾ | ਦੇਤਾ | ਚਲਤੋ=ਚਲਤਉ | ਜਾਤੇ=ਜਾਤਉ | ਪੀਅੰਤੁ | ਭਵੰਤਾ',
     'ਚਲਤਾ/ਚਲਤੁ = moving | ਜੀਵਤਾ/ਜੀਵਤੁ = living | ਜਾਵਤਾ/ਜਾਤਾ = going | ਹੋਤਾ = being | ਦੇਤਾ = giving | ਪੀਅੰਤੁ = drinking',
     'shackle_L22_p139_p140'),
    ('word_form', 'present_participle_d_forms',
     'D-forms of the present participle are marked by [-dā], declined like adjective declension AII. Consonant stems add [-adā], with occasional extended [-emdā] and rare [-andā]. Vowel stems usually add [-dā] directly with the stem vowel nasalized; transitive stems in [-ā-] usually take extended [-indā], all stems in [-ā-] may also take [-nvadā], and common stems in [-av-] may take [-aundā]. Masculine singular direct in [-dā] may have variant [-do].',
     'ਕਰਦਾ | ਜਾਣਦਾ | ਕਰੇਂਦਾ=ਕਰੰਦਾ | ਤਰੰਦਾ | ਜਾਂਦਾ | ਦੇਂਦਾ | ਕਮਾਇੰਦਾ | ਪਾਇੰਦਾ | ਕਮਾਵਦਾ=ਕਮਾਇੰਦਾ | ਭਾਵਦਾ | ਪਉਂਦਾ | ਭਉਂਦਾ | ਜਾਂਦੇ=ਜਾਂਦਾ',
     'ਕਰਦਾ = doing | ਜਾਣਦਾ = knowing | ਜਾਂਦਾ = going | ਦੇਂਦਾ = giving | ਕਮਾਇੰਦਾ = practising | ਪਉਂਦਾ = falling | ਭਉਂਦਾ = wandering',
     'shackle_L22_p140_p141'),
    ('tense', 'present_participle_as_present_tense',
     'The present participle may function as a present tense, just as the past participle functions as a past tense. It may also be used with "to be" as a present tense without changing meaning. It agrees with the subject in gender and number for both transitive and intransitive verbs, but because a finite present tense exists, this use is less common than the past participle as finite past.',
     'ਮੇਰਾ ਪ੍ਰਭੁ ਸਭੁ ਕਿਛੁ ਜਾਣਦਾ | ਜੀਉ ਤਪਤੁ ਹੈ ਬਾਰੈ ਬਾਰ',
     'ਜਾਣਦਾ = knows | ਤਪਤੁ ਹੈ = burns, is burning',
     'shackle_L22_p141'),
    ('word_form', 'present_participle_adjectival_functions',
     'The present participle is formally an adjective and may be used adjectivally, with meanings such as "doing, living, going, burning" according to the verb and context.',
     'ਜੀਵਤਾ | ਚਲਤਾ | ਕਰਦਾ | ਜਾਣਦਾ',
     'ਜੀਵਤਾ = living | ਚਲਤਾ = moving | ਕਰਦਾ = doing | ਜਾਣਦਾ = knowing',
     'shackle_L22_p141_p142'),

    # LESSON 23: §230-§232
    ('word_form', 'present_participle_as_adverb_agreeing',
     'The present participle is frequently used adverbially to describe an action occurring at the same time as the main verb. When the sentence subject is a noun or pronoun in direct case, the participle agrees with it in gender and number.',
     'ਢੂੰਢਤ ਢੂੰਢਤ ਹਉ ਫਿਰੀ | ਜੇ ਓਇ ਦਿਸਹਿ ਨਰਕਿ ਜਾਂਦੇ',
     'ਢੂੰਢਤ ਢੂੰਢਤ = seeking and searching | ਜਾਂਦੇ = going, agreeing with plural subject',
     'shackle_L23_p145'),
    ('word_form', 'fixed_adverbial_present_participle',
     'Where there is no direct-case subject for the participle to agree with, a fixed adverbial present participle is used. This occurs especially in impersonal sentences and ergative constructions, where the logical subject is locative/agentive or oblique. The form is formally masculine oblique: T-participles may use [-te], [-tiāṃ], or [-ta]; D-participles may use [-de] or [-diāṃ], all in free variation.',
     'ਜੀਵਤੇ / ਜੀਵਤਿਆਂ / ਜੀਵਤ | ਜੀਵਦੇ / ਜੀਵਦਿਆਂ | ਜੀਵਦਿਆਂ ਇਉ ਮਰੀਐ | ਕਰਤੇ ਮੁਕਤਿ | ਖੋਜ ਖੋਜ ਅੰਮ੍ਰਿਤੁ ਪੀਆ',
     'ਜੀਵਦਿਆਂ = while living | ਕਰਤੇ = by uttering/doing | ਖੋਜ ਖੋਜ = searching and searching | ਪੀਆ = drank (ergative context requires adverbial participle)',
     'shackle_L23_p145_p146'),
    ('principle', 'adverbial_participle_repetition_and_hi',
     'Repeated adverbial present participles give a sense of continual action, like repeated absolutives. The adverbial present participle may be followed by emphatic [hī], stressing immediacy of the action.',
     'ਖੋਜ ਖੋਜ | ਜਨਮਤ ਹੀ ਦੁਖੁ ਲਾਗੈ',
     'ਖੋਜ ਖੋਜ = searching and searching | ਜਨਮਤ ਹੀ = right on being born, as soon as one is born',
     'shackle_L23_p146'),
    ('word_form', 'adverbial_past_participle',
     'Unlike the present participle, the past participle is not normally used adverbially in agreement with a direct-case subject. A less common adverbial past participle can be formed with endings [-e] or [-iāṃ]. The commonest occurrence is in the phrase "dead or alive"; it is also used in impersonal sentences for an action completed before the main verb, and especially in phrases with [binu]=[viṇu] "without, except by, unless".',
     'ਮੁਇਆ=ਮੂਆ / ਮੂਏ / ਮੁਇਆਂ | ਮੁਇਆ ਜੀਵਦਿਆ | ਧੋਤਿਆ ਜੂਠਿ ਨ ਉਤਰੈ | ਬਿਨੁ ਗੁਰ ਸੇਵੇ ਘਾਟੇ ਘਾਟਿ | ਵਿਣੁ ਪੁਛਿਆ ਹੀ ਲੈ ਜਾਇ',
     'ਮੂਏ/ਮੁਇਆਂ = dead (adverbial) | ਮੁਇਆ ਜੀਵਦਿਆ = dead or alive | ਧੋਤਿਆ = having washed | ਬਿਨੁ ਗੁਰ ਸੇਵੇ = unless one serves the Guru | ਵਿਣੁ ਪੁਛਿਆ = without asking',
     'shackle_L23_p147'),

    # LESSON 24: §240
    ('number', 'numerals_cardinals_declension',
     'Apart from [ikku]=[eku] "one", low cardinal numerals have a simpler declension: several direct forms may be in free variation; at most they have an oblique form used before a noun in oblique or locative, and emphatic direct forms with lengthened final vowels meaning "both, all three, all four", etc.',
     'ਇਕੁ=ਏਕੁ | ਦੁਇ / ਦੁਹ / ਦੋਵੇ=ਦੋਇ | ਤ੍ਰੈ=ਤਿੰਨਿ / ਤਿਹੁ / ਤੀਨੇ | ਚਾਰਿ / ਚਹੁ / ਚਾਰੇ | ਪੰਚ=ਪੰਜਿ / ਪੰਜਾਂ / ਪੰਚੇ=ਪੰਜੇ | ਛਿਆ=ਖਟ | ਸਤ=ਸਾਤ=ਸਤਤ | ਅਠ=ਆਠ=ਅਸਟ | ਨਉ=ਨਵ | ਦਸ',
     'ਦੁਇ = two | ਦੁਹ = oblique two | ਦੋਵੇ/ਦੋਇ = both | ਤੀਨੇ = all three | ਚਾਰੇ = all four | ਪੰਜਾਂ = oblique five',
     'shackle_L24_p152'),
    ('word_form', 'numerals_ordinals',
     'Ordinal numerals correspond to English "first, second, third", etc., and are inflected as adjectives of declension AII.',
     'ਪਹਿਲਾ | ਦੂਜਾ | ਤੀਜਾ | ਚਉਥਾ | ਪੰਜਵਾਂ | ਛਿਅਵਾਂ | ਸਤਵਾਂ | ਅਠਵਾਂ | ਨਾਵਾਂ | ਦਸਵਾਂ',
     'ਪਹਿਲਾ = first | ਦੂਜਾ = second | ਤੀਜਾ = third | ਚਉਥਾ = fourth | ਪੰਜਵਾਂ = fifth | ਦਸਵਾਂ = tenth',
     'shackle_L24_p152'),
]

existing = cur.execute(
    "SELECT COUNT(*) FROM grammar_rules WHERE source >= 'shackle_L17' AND source < 'shackle_L25'"
).fetchone()[0]
if existing:
    raise SystemExit(f'Abort: {existing} Shackle L17-L24 rules already exist')

cur.executemany(
    '''
    INSERT INTO grammar_rules (category, pattern, meaning, example_word, example_meaning, source)
    VALUES (?, ?, ?, ?, ?, ?)
    ''',
    rules,
)

conn.commit()
print(f'Added {len(rules)} rules')
print(f'Total grammar_rules: {cur.execute("SELECT COUNT(*) FROM grammar_rules").fetchone()[0]}')
conn.close()
